### ISSUE TITLE
datasets download failed

### ISSUE THREAD

**Issue by xy-adams** [dmis-lab/cookingsense#1]

**Comment by xy-adams** [comment]
Having trouble downloading the dataset from your GitHub project; links aren't working. Can you provide an alternative link or check the current ones?

**Comment by dongheechoi** [comment]
https://www.dropbox.com/scl/fi/v2f7zaym12yusacvbddhy/datasets.zip?rlkey=36x1rcwmyup7qb85eadv2ooe9&st=ny3tdq9i&dl=0

Have you tried this link? I tried with an incognito window and it looks fine for me.

**Comment by xy-adams** [comment]
Thank you very much for your response. I've tried the link multiple times, but I encounter an error just before the download completes, stating "Unable to download, an issue occurred, please retry or contact your organization."

**Comment by dongheechoi** [comment]
I have added a google drive link for the dataset, if you still have a problem with downloading the dataset, please let me know.

https://drive.google.com/file/d/1R8lwj2YWuwf248ice2gj-SpCUb-JSLsn/view?usp=sharing

**Comment by dongheechoi** [comment]
I will close this issue since I haven't received any update.

**Comment by xy-adams** [comment]
Once again, I want to extend a heartfelt thank you. With your assistance, I've been able to resolve the issues I was facing.
