### ISSUE TITLE
Privacy Error when accessing research paper on README.md

### ISSUE THREAD

**Issue by kuds** [dmis-lab/cookingsense#2]
When I try to access the CookingSense paper on README.md, Google Chrome and Edge give me a privacy error. Should the link be changed from [https://anthology.aclweb.org/2024.lrec-main.354/](https://anthology.aclweb.org/2024.lrec-main.354/) to [https://aclanthology.org/2024.lrec-main.354/](https://aclanthology.org/2024.lrec-main.354/)?

**Comment by dongheechoi** [comment]
Thank you for your suggestion. README has been updated.
